apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bb56jmkf3-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/bb56jmkf3-dotnet-basic